"""Add equipped_character

Revision ID: 5abfa8a797c5
Revises: 
Create Date: 2026-02-04 19:49:15.241731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abfa8a797c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_users')
    op.drop_table('table_stocks')
    op.drop_table('stock_transactions')
    op.drop_table('user_transaction_stocks')
    with op.batch_alter_table('dbs2_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_wallet_btc', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('_wallet_eth', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('_wallet_sol', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('_wallet_ada', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('_wallet_doge', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('equipped_character',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("'chillguy'"))
        batch_op.alter_column('_scrap_crypto_miner',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_whackarat',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_laundry',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_ash_trail',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_infinite_user',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_has_seen_intro',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('_updated_at')
        batch_op.drop_column('_created_at')
        batch_op.drop_column('_escaped')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dbs2_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_escaped', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('_created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('_updated_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('_has_seen_intro',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_infinite_user',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_ash_trail',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_laundry',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_whackarat',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('_scrap_crypto_miner',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('equipped_character',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'chillguy'"))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('_wallet_doge')
        batch_op.drop_column('_wallet_ada')
        batch_op.drop_column('_wallet_sol')
        batch_op.drop_column('_wallet_eth')
        batch_op.drop_column('_wallet_btc')

    op.create_table('user_transaction_stocks',
    sa.Column('_user_id', sa.INTEGER(), nullable=False),
    sa.Column('_transaction_id', sa.INTEGER(), nullable=False),
    sa.Column('_stock_id', sa.INTEGER(), nullable=False),
    sa.Column('_quantity', sa.INTEGER(), nullable=False),
    sa.Column('_price_per_stock', sa.FLOAT(), nullable=False),
    sa.Column('_transaction_amount', sa.INTEGER(), nullable=False),
    sa.Column('_transaction_time', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['_stock_id'], ['table_stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['_transaction_id'], ['stock_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['_user_id'], ['stock_users.id'], ),
    sa.PrimaryKeyConstraint('_user_id', '_transaction_id', '_stock_id')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('_user_id', sa.INTEGER(), nullable=False),
    sa.Column('_transaction_type', sa.VARCHAR(length=255), nullable=False),
    sa.Column('_quantity', sa.INTEGER(), nullable=False),
    sa.Column('_transaction_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['_user_id'], ['stock_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_stocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('_symbol', sa.VARCHAR(length=255), nullable=False),
    sa.Column('_company', sa.VARCHAR(length=255), nullable=False),
    sa.Column('_quantity', sa.INTEGER(), nullable=False),
    sa.Column('_sheesh', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('_uid', sa.VARCHAR(length=255), nullable=False),
    sa.Column('_stockmoney', sa.INTEGER(), nullable=False),
    sa.Column('_accountdate', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['_uid'], ['users._uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
